/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nezet;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.Auto;
public class AutoGui extends javax.swing.JFrame {

    private List<Auto> autok;
    
    public AutoGui() {
        initComponents();
         autok = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        cmbRendszam = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtFiz_Mod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTav = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOssz = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBorr = new javax.swing.JTextField();
        chDohanyzo = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnu_xyz456 = new javax.swing.JMenuItem();
        mnuDohanyzo = new javax.swing.JMenuItem();
        mnuleghosszabFuv = new javax.swing.JMenuItem();
        mnuDolgozott = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rendszam:");

        jLabel2.setText("Datum:");

        txtDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumActionPerformed(evt);
            }
        });

        cmbRendszam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRendszamActionPerformed(evt);
            }
        });

        jLabel3.setText("Fizetési Mód:");

        jLabel4.setText("Táv:");

        txtTav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTavActionPerformed(evt);
            }
        });

        jLabel5.setText("Összeg:");

        txtOssz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOsszActionPerformed(evt);
            }
        });

        jLabel6.setText("Borravaló:");

        chDohanyzo.setText("Dohányzó");

        jMenu1.setText("File");

        jMenuItem1.setText("Betöltés");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Feladatok");

        mnu_xyz456.setText("xyz-456 össz bevétel");
        mnu_xyz456.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_xyz456ActionPerformed(evt);
            }
        });
        jMenu5.add(mnu_xyz456);

        mnuDohanyzo.setText("Autok amiben lehet dohányozni");
        mnuDohanyzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDohanyzoActionPerformed(evt);
            }
        });
        jMenu5.add(mnuDohanyzo);

        mnuleghosszabFuv.setText("auto a leghosszabb fuvarral");
        mnuleghosszabFuv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuleghosszabFuvActionPerformed(evt);
            }
        });
        jMenu5.add(mnuleghosszabFuv);

        mnuDolgozott.setText("2022.12.31-ei dolgozók");
        mnuDolgozott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDolgozottActionPerformed(evt);
            }
        });
        jMenu5.add(mnuDolgozott);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatum))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbRendszam, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtFiz_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTav)
                            .addComponent(txtOssz)
                            .addComponent(txtBorr))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chDohanyzo)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbRendszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFiz_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTav, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtOssz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBorr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chDohanyzo)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTavActionPerformed

    private void txtOsszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOsszActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOsszActionPerformed

    private void txtDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try 
        {
            List<String> sorok = Files.readAllLines(Path.of("fuvarok.txt"));
            
            for (int i = 2; i < sorok.size(); i++) 
            {
                String sor = sorok.get(i);
                Auto auto = new Auto(sor);
                autok.add(auto);
                cmbRendszam.addItem(auto.getRednszam()+ " / " );
               
            }
            
            megjelenit(autok.getFirst());
            
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(Auto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cmbRendszamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRendszamActionPerformed
        int i = cmbRendszam.getSelectedIndex();
        Auto auto = autok.get(i);
        megjelenit(auto);
    }//GEN-LAST:event_cmbRendszamActionPerformed

    private void mnu_xyz456ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_xyz456ActionPerformed
        String rendszam = "xyz-456";
        JOptionPane.showMessageDialog(rootPane, "Az %s rendszámú autó összbevétele: %d Ft".formatted(rendszam, osszbevetel(rendszam)));
        
    }//GEN-LAST:event_mnu_xyz456ActionPerformed

    private void mnuDohanyzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDohanyzoActionPerformed
        
            JOptionPane.showMessageDialog(rootPane, "%s lehet minden autóban dohányozni.".formatted(dohanyzas()?"Nem":"Igen, "));
        
    }//GEN-LAST:event_mnuDohanyzoActionPerformed

    private void mnuleghosszabFuvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuleghosszabFuvActionPerformed
        
        int leghosszabbIndex = leghosszabbFuvarIndex();
        JOptionPane.showMessageDialog(rootPane, "A leghosszabb fuvar a(z) %s rendszámú autóé volt (%.2 km)".formatted(autok.get(leghosszabbIndex).getRednszam(), autok.get(leghosszabbIndex).getTav()));
        
    }//GEN-LAST:event_mnuleghosszabFuvActionPerformed

    private void mnuDolgozottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDolgozottActionPerformed
       
        List<String> dolgozok = kikDolgoztak("2022.12.31.");
        String rendszamok = "";

        for (int i = 0; i < dolgozok.size(); i++) 
        {
            rendszamok += dolgozok.get(i) + " ";
        }
        
        JOptionPane.showMessageDialog(rootPane, "Aznap %s dolgozott.".formatted(rendszamok));
        
    }//GEN-LAST:event_mnuDolgozottActionPerformed

   private int osszbevetel(String rendszam)
    {
        int osszbevetel = 0;
        for (int i = 0; i < autok.size(); i++) 
        {
            if(autok.get(i).getRednszam().equals(rendszam))
            {
                osszbevetel += autok.get(i).getOsszeg() + autok.get(i).getBorravalo();
            }
        }
        return osszbevetel;
    }
    
    private boolean dohanyzas()
    {
        int N = autok.size();
        int i = 0;
        
        while(i < N && autok.get(i).getDohanyzo())
        {
            i++;
        }
        return i < N;
    }
    
    private int leghosszabbFuvarIndex()
    {
        int maxxIndex = 0;
        
        for (int i = 0; i < autok.size(); i++) 
        {
            if(autok.get(i).getTav() > autok.get(maxxIndex).getTav())
            {
                maxxIndex = i;
            }
        }
        //System.out.println(maxxIndex);
        return maxxIndex;
    }
    
    private List<String> kikDolgoztak(String datum)
    {
        List<String> dolgoztak = new ArrayList<>();
        
        for (int i = 0; i < autok.size(); i++) 
        {
            if(autok.get(i).getDatum().equals(datum) && !(dolgoztak.contains(autok.get(i).getRednszam())))
            {
                dolgoztak.add(autok.get(i).getRednszam());
            }
        }
        //System.out.println(dolgoztak);
        return dolgoztak;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoGui().setVisible(true);
            }
        });
    }
    private void megjelenit(Auto auto) 
    {
        txtFiz_Mod.setText(auto.getFiz_Mod());
        txtTav.setText(auto.getTav() + "");
        txtOssz.setText(auto.getOsszeg() + "");
        txtBorr.setText(auto.getBorravalo() + "");
        chDohanyzo.setSelected(auto.getDohanyzo());
        txtDatum.setText(auto.getDatum()+ "");
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chDohanyzo;
    private javax.swing.JComboBox<String> cmbRendszam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnuDohanyzo;
    private javax.swing.JMenuItem mnuDolgozott;
    private javax.swing.JMenuItem mnu_xyz456;
    private javax.swing.JMenuItem mnuleghosszabFuv;
    private javax.swing.JTextField txtBorr;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtFiz_Mod;
    private javax.swing.JTextField txtOssz;
    private javax.swing.JTextField txtTav;
    // End of variables declaration//GEN-END:variables
}
